### ISSUE TITLE
Epic►001►Navigation Bar System v3

### ISSUE THREAD

**Issue by VillageHubertChen** [V-Squared/V-Squared.github.io#47]
- [x] HC, LC: Brainstorm on v3 features and implementation
- [x] HC: Document this project in description below
- [x] LC: Hack a design that comes close to the below ideas, but is a quick implementation based on what we have
- [x] Implement Milestone 1: Essential Features
  - [x] HC: Create [YAML file for Board-Bar](7#issuecomment-218051079)
  - [x] Create [YAML file for Book-Bar](#issuecomment-218051115)
  - [x] Add styling to Article-Bar
  - [x] Add a Book-Bar Jumbotron in top of Article Bar
  - [x] Add Title "Articles" in Article Bar under the Book Bar Jumbotron
    - Read subtitle from Book-Bar.yaml file
  - [x] Board Jumbotron Content as per v3 design
  - [x] Move Bread Crumbs into Article Body
  - [x] Make Book-Bar sticky
  - [x] Make Article-Bar sticky
  - [x] Test on Lukas Machine
  - [x] Push to GitHub. Trigger HC for Testing. HC adds more pages, experience navigation
  - [x] delete folder: /roadMap/
- [x] Implement Milestone 2: Nice Features
  - [x] Do → [Tweak Layout of Article-Bar](#issuecomment-218639889)
  - [x] Add [Contents-Bar](#issuecomment-218665726)
  - [x] Implement: Article Front Matter and its Styling → #50 
  - [x] Update all Front Matter in all Plan Articles to the new Syntax as per → #50
  - [x] Do → [Layout Tweak Article-Bar](#issuecomment-218639889)
  - [x] Layout indicates relationship of menu items
  - [x] Style the Article as card
  - [x] Make → [Nav Bar System Responsive](#issuecomment-218672562) to work on mobile
  - [x] Implement → [Edit & GitHub FAB](#issuecomment-218737310)
# v3 Nav Bar System
## Features, Placement and Order
1. Jumbotron of V²Site shows:
   1. Board-Title
   2. Board-Sub-Title (from Tooltip)
   3. Board-Visual (50% darkened and colored in Board Color. In Background, Line Art)
2. Choosing the Board automatically loads the Intro Page (already done)
3. Each Article has an Article Head
   1. Bread Crumbs
   2. Article-Title
   3. Article-Visual
   4. Article-Sub-Title
# v3 vs. v2 Features
- Sits on top of v2
- Cleans up inconsistencies of v2
  - Navigation feels better by following rule: Choice effects below only
  - Bread Crumbs are placed with Article. It is the path to the Article.
  - Colors in Navigation bar group the content correctly
  - Layout clearly indicates which menu item will modify what other menu items
    - upstream / downstream relationship of menu items are visually indicated
- Adds feature of _Navigation Preview_ for Level 1
- Level 1 navigation gains a Jumbotron
- Implements _ToC Bar_ (specified in v2 but not yet implemented)
- Adds One Jumbotron each for Level 1 and 2
- Article takes center stage
  - centered horizontally
  - Why background marks Article
  - Article Title is very easy and fast to find
  - Article gains Article Head: Title, Bread-Crumbs, Title-Image and Sub-Title
- Article width is not too wide
- Modern design as we use full width of big display:
  Article Navigation + Article Body + Content Navigation  
# Hero Pages
## Links and Names to Hero Pages
- [Manek](http://gauravmanek.com/blog/2014/07/16/templating-with-jeykll.html)
- [Google►Dev](https://developers.google.com/schemas/tutorials/apps-script-tutorial)
### From Manek
- Layout / borders of fill colors indicate relationships of menu items
- Put the article in center stage, make the navigation the frame
### From Google►Dev
- Responsive design: How Nav Bars flow, collapse and move
- Level 1 Jumbotron aligned to left side
# Colors

| Item | Color Weight |
| :-- | :-- |
| Board-Bar | 700 |
| Selected Board-Bar Item<br>Board Jumbotron<br>Book-Bar | 500 |
| Article-Bar | 300 |
# Navigation Preview
- when hovering over Board-Bar Menu Item the Board Jumbotron is updated with the corresponding content
- Functionality is made by JavaScript that is in board-bar.html file
- Data is contained in board-bar.json file
# Definition of Jumbotron
- A jumbotron indicates a big box for calling extra attention to some special content or information.
- http://www.w3schools.com/bootstrap/bootstrap_jumbotron_header.asp
# Changes vs v2
## Big Visual Bread Crumbs for Level 1 and 2
# Reference
- → #42 Navigation Bar System v2
- → #44 Library Metaphor for V² Navigation

**Comment by VillageHubertChen** [comment]
# YAML file for Board-Bar

## File Name and Location
- **Name:** "board-bar.yml"
- **Location:** "_data"

## Content of board-bar.yml

``` yaml
- menu: Standards
  url: /standards/
  title: The Missing Standard
  subtitle: All missing standards to find parts, build, upgrade, maintain and repair a modular Mini / All-In-One PC.
- menu: Products
  url: /products/
  title: Trailblazer Products
  subtitle: Real products available early on, showing what you can build with V² Standards. Buy today what is to become mainstream tomorrow.
- menu: Makers
  url: /makers/
  title: For Makers
  subtitle: Everything you need to develop your new products faster at lower cost.
- menu: DIY
  url: /diy/
  title: For DIY
  subtitle: PC Know How & Tools.
- menu: Retail
  url: /reatil/
  title: For Retail
  subtitle: Lower your cost and increase computer sales.
- menu: Apps
  url: /apps/
  title: Apps
  subtitle: V² Open Source Web Apps simplify experiencing or building V² PCs.
- menu: Spreading
  url: /spreading/
  title: Spreading the Word of V²
  subtitle: How to tell the story of a smaller, quieter, more modular and upgradable PC and how to get it into the hands of the user.
- menu: Plan
  url: /plan/
  title: Plan
  subtitle: How V² will improve your life, how we make it happen and how you can help.
- menu: Organization
  url: /organization/
  title: Organization
  subtitle: How you can benefit from or contribute to V² and who are the people making it happen, why and how.
```

**Comment by VillageHubertChen** [comment]
# YAML file for Book-Bar

## File Name and Location
- **Name:** "book-bar.yml"
- **Location:** 
  1. go to <> Code directory of the repository hosting your Jekyll Site
  2. enter folder: "_data"
  3. This contains one folder for each _Book_ of your _Site_. Pick the Book you want to edit
  4. Each of above folders contains the "book-bar.yml" file with content corresponding to its folder

## Example Content of book-bar.yml of V² > Plan

``` yaml
- menu: True North
  url: /true-north/
- menu: Road Map
  url: /road-map/
  desc: >
    How to reach True North via consecutive Campaigns.
  subitems:
    - menu: Strategy
      url: /road-map/strategy/
    - menu: Campaign 1
      url: /road-map/campaign01/
    - menu: Campaign 2
      url: /road-map/campaign02/
    - menu: Campaign 3
      url: /road-map/campaign03/
- menu: Dashboard
  url: /dashboard/
- menu: Flow
  url: /flow/
- menu: Agile
  url: /agile/
  desc: >
    Generic Agile Development and Toyota Production System for Github Organizations.
  subitems:
    - menu: Getting Started
      group: 
        - menu: V²Agile Workflow on GitHub
          url: /agile/getting-started/agile-workflow/
        - menu: V²Sprint Workflow on GitHub
          url: /agile/getting-started/sprint-workflow/
        - menu: Roles & Communication
          url: /agile/getting-started/roles/
        - menu: Testing
          url: /agile/getting-started/iterations/
    - menu: Fundamentals
      group:
        - menu: Agile Development Primer
          url: /agile/fundamentals/agile-primer/
        - menu: Motivation by Design
          url: /agile/fundamentals/motivation/
    - menu: Developing / Evaluating
      group:
        - menu: Solving today's Problems
          url: /agile/developing/solving-problems/
        - menu: Multi Repo Management
          url: /agile/developing/multi-repo/
        - menu: Adding SCRUM to GitHub
          url: /agile/developing/adding-scrum/
        - menu: Adding Dashboard to GitHub
          url: /agile/developing/dashboard/
        - menu: Developing V²Plan
          url: /agile/developing/developing/
        - menu: Adapting V²Plan
          url: /agile/developing/adapting/
    - menu: Reference
      group:
        - menu: Features of V²Plan
          url: /agile/reference/features/
        - menu: V² Plan Reference
          url: /agile/reference/reference/
```

## Notes
- Max Lengths of Menu Item name: 13 Char
- Max Lengths of Article Name: 26 char. Article Name is the Menu Name in Level 3 and 4
